### ISSUE TITLE
User interface and usage issue/points

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/alces-flight-center#37] opened 2018-01-19 11:21 UTC
This issue is to track certain UI and usage "issues" that I come across in the general usage of flight-center as discussed with @mjtko and @bobwhitelock.

 - When selecting a site, the text of the table showing the open support tickets for that site could do with a slight rejig - for example at the moment for certain sites it will read "Open The University of Foo tickets" - which probably makes sense for certain sites, but doesn't make sense for others. Possibly rejig that text to "Open Tickets - The University of Foo".

 - When a ticket is opened in RT, the contents does not show the requestor for that ticket, although there may only be two site admins, we'd currently have to go back to flight-center to find out which user initiated the ticket. Could we possibly just have this as a field in the head of the ticket for when we're responding after the ticket has been opened?

I'll add more as time goes on!

**Comment by RuanEllis** [comment] 2018-01-19 12:09
When tickets are created with the same service/issue, the title of the ticket ends up being identical which is somewhat difficult to differentiate between the tickets, but also in an email client with "conversation view" - this ends up with the two tickets being threaded with obvious confusing side effects! @mjtko has tested placing a unique identifier such as `UNIQUE01` and `UNIQUE02`(which you'll probably see in your email inbox if you subscribe to the Alces Helpdesk) at the end of each ticket subject that's created which appears to prevent this from happening. Turning off conversation view naturally fixes this, but even accessing directly from RT, it's somewhat difficult to tell apart the two tickets.

**Comment by bobwhitelock** [comment] 2018-01-19 12:25
@RuanEllis thanks for logging the issues you've been running into.

For your latest comment, have you or @mjtko worked out the criteria are for when things will be threaded vs not? Presumably the unique prefix with the RT ticket ID is insufficient (e.g. `[helpdesk.alces-software.com #11460]`? But a unique suffix like ` [UNIQUE02]` does work (as far as I can tell from the emails I've received)?

**Comment by RuanEllis** [comment] 2018-01-19 12:31
@bobwhitelock - It appears that the email client is looking at the ending, or at least, a large majority of the subject line to see how much difference there is. A combination of those two items being changed causes the client to split the threads - I don't know the exact algorithm that the client used, but from testing, this appears to be sufficient. I don't know how we want to implement this, whether we put a random string in that identifies the ticket, or whether we decide to place the first few lines of text in? @mjtko may have more of an opinion on this.

**Comment by bobwhitelock** [comment] 2018-01-19 12:50
Is this just something odd/clever gmail's doing? Or have you noticed similar in another client?

For fixing this, some options for things we could add to created tickets spring to mind:

- add a random suffix - would work, but might be slightly confusing for customers and doesn't help much for distinguishing cases in RT;

- add a timestamp - I imagine this would work the same as above, but is a slightly more meaningful string, still not that useful for us or customers though;

- add some text from the case details - doing this well would be the nicest for customers and us in RT I imagine, but an issue with this is that we normally have standard templates for details to be included in the case, so including this would mean:
	- we have short but still similar text in every RT issue title, as it includes part of the details template;
	- we include a lot of text in issue titles;
	- we extract some distinct text from the case details, discarding parts which come from the details template, and include this (this would be the nicest but most work I think).

**Comment by RuanEllis** [comment] 2018-01-19 13:46
This is something "clever" that gmail is doing, however, the same behaviour is seen in other email clients (or at least, in the cases tested, the behaviour appeared the same...).

To me, the random string is preferable at present as creates us a method to differentiate the tickets based upon something that's totally unrelated to the time/subject. By this issue's nature, the contents of the ticket is likely to be quite similar, so even the detection of certain distinct text from the case is likely to be somewhat difficult also! 

The timestamp option is possibility, however, I'd say it's realistically only as useful as a random string, the deciphering of this when reading the ticket is probably harder than simply looking at a random string? 

Just my feelings on this - others may have differing opinions!

**Comment by bobwhitelock** [comment] 2018-01-19 14:09
OK, thanks for the explanation - a random string should be pretty straightforward to add, and we'll do that at some point soon unless anyone thinks a different approach would be better.

**Comment by bobwhitelock** [comment] 2018-01-25 15:18
We should also address point (2) here: https://alces.slack.com/archives/C72GT476Y/p1516893053000534 (which is a user-reported duplicate of https://trello.com/c/bG8bgcvX/147-case-details-look-shown-without-formatting-in-cases-table).

**Closed** 2018-01-31 11:08 UTC
Labels: UI tweaks

**Comment by bobwhitelock** [comment] 2018-01-31 11:29
@RuanEllis all the issues mentioned in this issue should now have been fixed and are deployed. Please open new issues for any new problems/suggestions you have :slightly_smiling_face:
