### ISSUE TITLE
Odd change issue description

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#537] opened 2018-08-17 12:23 UTC
New case -> Choose 'Hardware Management' -> Choose 'Other' -> Create a case

Case is created with 'Suspected hardware issue' as the issue, but if you change it you get...

![screen shot 2018-08-17 at 13 23 01](https://user-images.githubusercontent.com/503613/44265971-b12d7680-a220-11e8-8251-1f43f8bbb14a.png)

Email to the customers said the same :(

**Comment by jamesremuscat** [comment] 2018-08-20 09:43
Couple of things at play here:

1. Rails magic fails to preselect the correct option in the issue dropdown. The issue is initially correctly set as "other" but it displays the first item in the list instead.
2. We don't filter out unchanged values before changing them.

**Comment by jamesremuscat** [comment] 2018-08-20 09:55
It goes deeper: the "Other" that gets selected on case creation is a different "Other" to the one that's made available in the dropdown.

**Comment by jamesremuscat** [comment] 2018-08-20 10:50
Turns out that 2. isn't the issue (although we don't do any such filtering, Rails does some for us) - it was genuinely changing the issue, just to one with the same name.

Pushed a fix for this that makes sure we're correctly determining which issues appear in the dropdown.

**Closed** 2018-08-20 15:30 UTC
