### ISSUE TITLE
Contract dates

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#480] opened 2018-08-07 11:03 UTC
Base managed support coverage runs between 2 dates and is mapped to a site. We need to stores and indicate these dates quite prominently to the users when viewing their account. At the moment it just needs to be highlighted when its expired, but going forward we'll want to send reminders / lock out accounts etc.

**Comment by jamesremuscat** [comment] 2018-08-07 11:04
Is this a duplicate of #403 ?

**Comment by ste78** [comment] 2018-08-07 11:07
yep its a duplicate. It need to be prominent thing though, not just on credit reports etc. A user needs to be left in no doubt when using the interface that their coverage has an end date.

**Comment by mjtko** [comment] 2018-08-16 18:16
Closed as duplicate of #403.  Enhancements for reminder emails and disabling access logged as #535 and #536.

**Closed by mjtko** 2018-08-16 18:16 UTC
