### ISSUE TITLE
Many warnings when rendering emails

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/alces-flight-center#461] opened 2018-07-30 13:36 UTC
Following the merging of #458, and specifically https://github.com/alces-software/alces-flight-center/pull/458/commits/9d5d28b407cfb8a3f96ed01d563eb2adfc759bfc, I get many warnings printed from Roadie each time an email is rendered. E.g.:

<details>

```
$ rspec spec/models/case_spec.rb:138Run options: include {:locations=>{"./spec/models/case_spec.rb"=>[138]}}

Randomized with seed 21307

Case
  Email creation on Case creation
Roadie: Cannot inline ".table-primary&gt;th" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-primary&gt;td" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-secondary&gt;th" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-secondary&gt;td" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-success&gt;th" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-success&gt;td" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-info&gt;th" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-info&gt;td" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-warning&gt;th" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-warning&gt;td" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-danger&gt;th" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-danger&gt;td" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-light&gt;th" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-light&gt;td" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-dark&gt;th" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-dark&gt;td" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-active&gt;th" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-active&gt;td" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-responsive-sm&gt;.table-bordered" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".markdown .table-responsive-sm&gt;table" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-responsive-md&gt;.table-bordered" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".markdown .table-responsive-md&gt;table" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-responsive-lg&gt;.table-bordered" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".markdown .table-responsive-lg&gt;table" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-responsive-xl&gt;.table-bordered" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".markdown .table-responsive-xl&gt;table" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".table-responsive&gt;.table-bordered" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
Roadie: Cannot inline ".markdown .table-responsive&gt;table" from "(inline)" stylesheet. If this is valid CSS, please report a bug.
    saves generated token

Top 1 slowest examples (1.37 seconds, 99.8% of total time):
  Case Email creation on Case creation saves generated token
    1.37 seconds ./spec/models/case_spec.rb:137

Finished in 1.37 seconds (files took 1.13 seconds to load)
1 example, 0 failures

Randomized with seed 21307
```

</details>

and this is from a single test/email render; many more are printed when more things are rendered.

Can anyone else reproduce? Vague guess is it looks like it might be trying to inline HTML-escaped CSS for some reason. Any ideas @jamesremuscat or @mjtko?

Also, after creating a Case the `/letter_opener` route made available by that PR does not show the email from that Case's creation - possibly related, if emails are failing to be rendered?

**Comment by jamesremuscat** [comment] 2018-07-30 13:50
AFAICT emails are being rendered and sent just fine, Roadie is leaving the styles it doesn't understand as un-inlined, so if that's not working for you there's a separate issue at play.

**Comment by jamesremuscat** [comment] 2018-07-30 14:44
@bobwhitelock Yes, that's correct. I don't remember having to do anything extra to make it work - I'm sure you've already tried, but do you need to restart your dev server?

**Comment by bobwhitelock** [comment] 2018-07-30 14:50
Had tried before, and retried just to be sure - still no emails, odd.

**Comment by jamesremuscat** [comment] 2018-07-30 14:58
@bobwhitelock Closing this issue since the many warnings are no more - I don't think they're the cause of your letter-opener problems.

**Closed** 2018-07-30 14:57 UTC
Labels: bug
